name: Vectorize

on:
  workflow_dispatch:
  push:
    branches:
      - bun-testing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vectorize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - uses: pguyot/arm-runner-action@v2
      # - uses: oven-sh/setup-bun@v1

      - name: test action
        id: vectorize
        uses: judegiordano/bun-reusable-workflow@v4
        with:
          example-input: "my custom input"

    env:
      EXCLUDE: "node_modules"
      INCLUDE: "**/*.md"