name: Vectorize

on:
  workflow_dispatch:
    inputs:
      include:
        description: 'Globs to include'
        required: false
        default: '**/*.md,**/*.yml'
      exclude:
        description: 'Globs to exclude'
        required: false
        default: '**/*node_modules/**/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vectorize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: vectorize project
        id: vectorize
        uses: judegiordano/reusable-workflows/vectorize-codebase@main
        with:
          include-pattern: ${{ github.event.inputs.include }}
          exclude-pattern: ${{ github.event.inputs.exclude }}

      - name: upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-artifact
          path: ./${{ github.sha }}.sqlite
          retention-days: 1
          include-hidden-files: true
          overwrite: true
          if-no-files-found: error